<a href="https://colab.research.google.com/github/tesseract97/pytorch_training/blob/main/02_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.3.1+cu121


In [8]:
#CPU TENSORS
first_tens = torch.tensor([[12,10,11,9],[13,15,14,16]])
second_tens = torch.tensor([[1,2,3,4],[5,6,7,8]])

add_tens = first_tens + second_tens

print(add_tens)
print(add_tens.size())

tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])
torch.Size([2, 4])


In [9]:
#CPU TENSORS
subtr_tens = first_tens - second_tens
print(subtr_tens)
print(subtr_tens.size())

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]])
torch.Size([2, 4])


In [3]:
if torch.cuda.is_available(): device = "cuda"
else: device = "cpu"
print(device)

cuda


In [5]:
tens_a = torch.tensor([[12,10,11,9],[13,15,14,16]], device=device)
tens_b = torch.tensor([[1,2,3,4],[5,6,7,8]], device=device)
tens_c = tens_a * tens_b
print(tens_c)
#the tensor is allocated to GPU, and the device variable is indicating which GPU is being used

tensor([[ 12,  20,  33,  36],
        [ 65,  90,  98, 128]], device='cuda:0')
