<a href="https://colab.research.google.com/github/tesseract97/pytorch_training/blob/main/03_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

tensor_from_list = torch.tensor([1,2,3,4,5])
tensor_from_tuple = torch.tensor((1,2,3,4,5))

print("1: ",tensor_from_list)
print("2: ",tensor_from_tuple)

tensor_from_array = torch.tensor(np.array([1,2,3,4,5]))

print("3: ",tensor_from_array)

1:  tensor([1, 2, 3, 4, 5])
2:  tensor([1, 2, 3, 4, 5])
3:  tensor([1, 2, 3, 4, 5])


In [10]:
print(torch.empty(3,4))
print(torch.ones(3,4))
print(torch.zeros(3,4))

print(torch.randint(5,10,(3,4)))
print(torch.rand(3,4))
tensor_c = torch.randn(3,4)
print(tensor_c)
#same dtype
print(torch.rand_like(tensor_c))

tensor([[-1.4554e-28,  4.4273e-41, -3.4905e+01,  3.2586e-41],
        [-1.2755e+01,  3.2586e-41, -2.9080e+01,  3.2586e-41],
        [ 0.0000e+00,  0.0000e+00, -2.8882e+01,  3.2586e-41]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[5, 9, 7, 9],
        [5, 5, 5, 6],
        [9, 8, 7, 6]])
tensor([[0.3389, 0.1720, 0.6210, 0.3795],
        [0.0148, 0.3226, 0.4084, 0.6283],
        [0.9393, 0.6238, 0.1719, 0.8278]])
tensor([[ 0.0481, -0.0476, -0.0140, -1.4289],
        [-1.2781,  0.1117,  1.6209,  0.3455],
        [ 0.5422, -0.5676, -0.2488,  0.0710]])
tensor([[0.2344, 0.6352, 0.8147, 0.2402],
        [0.7894, 0.3118, 0.5096, 0.3776],
        [0.9049, 0.3185, 0.8841, 0.6474]])


In [16]:
first_tensor = torch.tensor([1,2,3,4])
second_tensor = torch.tensor([[1,2],[2,3],[3,4]])

#device location
print(first_tensor.device)
#check dtype
print(first_tensor.dtype)
#check shape
print(first_tensor.shape)
#check dim
print(first_tensor.ndim)
print(second_tensor.ndim)

cpu
torch.int64
torch.Size([4])
1
2


In [26]:
tens_int = torch.tensor([1,2,3,4,5], dtype=torch.int8)
print(tens_int.dtype)

tens_float= torch.tensor([1,2,3,4,5], dtype=torch.float32)
tens_update = tens_int.float()
print(tens_update.dtype)
tens_float.to(dtype=torch.int16)

torch.int8
torch.float32


tensor([1, 2, 3, 4, 5], dtype=torch.int16)

In [5]:
torch.manual_seed(111)
torch.rand(3,3)

torch.randint(1,20,(4,4))

tensor([[ 4,  7, 17, 19],
        [ 4, 13, 19,  4],
        [16,  6, 19,  2],
        [ 4, 11, 10, 11]])

In [13]:
starting_tensor = torch.zeros(2,5)
starting_tensor

torch.manual_seed(111)
rand_tensor = torch.rand_like(starting_tensor)
rand_tensor

ones_tensor = torch.ones_like(starting_tensor)
ones_tensor

torch.full_like(starting_tensor,7)
torch.full((2,3), 7)

tensor([[7, 7, 7],
        [7, 7, 7]])