<a href="https://colab.research.google.com/github/tesseract97/pytorch_training/blob/main/04_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

tens_a = torch.tensor([1,2,3,4,5,6])
#indexing
print(tens_a[2])
print(tens_a[2].item())

tensor(3)
3


In [12]:
#slicing is start, end, step like normal
tens_a[2:4]

tens_b = torch.tensor([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
tens_b[0,1:2]
tens_b[tens_b<11]

#adds dimension
torch.stack((tens_b, tens_b))

first_tens, second_tens, third_tens = torch.unbind(tens_b)
print(first_tens)

tensor([1, 2, 3, 4, 5])


In [15]:
#pointwise operations
#each point and return new tensor

#add, mul, div, neg, true_divide
#ceil, clamp, floor
#logical function
#trig

a= torch.tensor([1,2,3,4,5])
b = torch.tensor([6,7,8,9,1])

print(a.div(b))

tensor([0.1667, 0.2857, 0.3750, 0.4444, 5.0000])


In [21]:
#reduction operations
#reduce dimensionality
#mean, mode, etc

#ONLY accepts floating types
c=torch.tensor([[1.,2.,3.,4.,5.],[12.,15.,31.,23.,44.]])

torch.mean(c)
torch.median(c)
torch.std(c)

tensor(14.4914)

In [23]:
#comparison functions
#compare everything inside a tensor
#or multiple tensors
#minimum, maximum, sort, test tensor status

torch.sort(c)


torch.return_types.sort(
values=tensor([[ 1.,  2.,  3.,  4.,  5.],
        [12., 15., 23., 31., 44.]]),
indices=tensor([[0, 1, 2, 3, 4],
        [0, 1, 3, 2, 4]]))

In [28]:
#lin alg
#matrix operations
#for DL

#scalar
#matrix/matrix

#similar to np lin alg but extended

first_tens =torch.tensor([1,2,3])
second_tens = torch.tensor([4,5,6])

dot_product = torch.matmul(first_tens, second_tens)
dot_product

#remember matrix mult rules
a = torch.tensor([[1,2,3],[2,3,4]])
b = torch.tensor([[3,4,5],[2,3,4],[2,3,4]])

matrix = torch.matmul(a, b)
matrix

tensor([[13, 19, 25],
        [20, 29, 38]])

In [31]:
first_ten = torch.randn(2,3)
second_ten = torch.randn(3,4)
third_ten = torch.randn(4,5)
fourth_ten = torch.randn(5,6)
fifth_ten = torch.randn(6,7)

torch.linalg.multi_dot((first_ten, second_ten, third_ten, fourth_ten, fifth_ten))

tensor([[-13.6641,  -1.8408,   7.2676,  -9.7606,  19.2920,   1.4892,   9.5755],
        [-16.7412,  -3.0578,  11.3318, -12.3846,  24.1973,   3.8206,  10.9886]])

In [32]:
#eigenvectors and eigenvalues

a = torch.randn(4,4)

print(a)
eigenvalues, eigenvectors = torch.linalg.eig(a)

print(eigenvalues)
print(eigenvectors)

tensor([[ 2.1855, -0.5300, -1.5343, -0.9688],
        [ 2.1436,  1.3374,  0.7119,  1.2197],
        [ 0.1221,  1.1858, -0.0601, -0.1931],
        [-0.0070,  0.4997, -0.3786,  0.7681]])
tensor([ 2.2564+1.5230j,  2.2564-1.5230j, -1.1398+0.0000j,  0.8580+0.0000j])
tensor([[ 0.1593+0.5946j,  0.1593-0.5946j, -0.3027+0.0000j, -0.1894+0.0000j],
        [ 0.7154+0.0000j,  0.7154-0.0000j,  0.6014+0.0000j, -0.2812+0.0000j],
        [ 0.2727-0.1423j,  0.2727+0.1423j, -0.6787+0.0000j, -0.5491+0.0000j],
        [ 0.0998-0.0687j,  0.0998+0.0687j, -0.2933+0.0000j,  0.7639+0.0000j]])


In [ ]:
#spectral operations
#data transformations


In [35]:
#automatic differentiation
#forward propagation
#backward propagation

#after we find loss function, we calculate the derivative
#update the weight parameters for smallest loss
#iterative optimization
#automatic differentiation
#partial derivatives

#numerical derivatives => computational costs, truncation errors, roundoff errors
#symbolic derivatives => limited to defined rules, explosion of symbolic terms

#SOOOO automatic differentiation
#composition of elementary functions
#chain rule

x = torch.autograd.Variable(torch.Tensor([2]), requires_grad=True)
y = torch.autograd.Variable(torch.Tensor([1]), requires_grad=True)
z = torch.autograd.Variable(torch.Tensor([5]), requires_grad=True)


a = x - y

f = z * a

f.backward()

print(x.grad)
print(y.grad)
print(z.grad)

tensor([5.])
tensor([-5.])
tensor([1.])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]) /  tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
